/**
 * icon-geom.ts — GENERATED by scripts/icon-build.mjs (do not hand-edit).
 * Canonical RAW (self-closing) inner geometry + viewBox per shared glyph. Used by
 * Icon.astro (expanded to match Astro's output) and iconSvg() (verbatim string).
 */
export interface IconGeom { vb: string; body: string; }
export const ICON_GEOM: Record<string, IconGeom> = {
  "moon-mark": { vb: "0 0 24 24", body: "<path d=\"M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8z\"/>" },
  "check": { vb: "0 0 24 24", body: "<polyline points=\"20 6 9 17 4 12\"/>" },
  "chevron-right": { vb: "0 0 24 24", body: "<path d=\"M9 6l6 6-6 6\"/>" },
  "chevron-left": { vb: "0 0 24 24", body: "<path d=\"M15 18l-6-6 6-6\"/>" },
  "arrow-up": { vb: "0 0 24 24", body: "<path d=\"M12 19V5M5 12l7-7 7 7\"/>" },
  "arrow-right": { vb: "0 0 24 24", body: "<path d=\"M5 12h14M13 5l7 7-7 7\"/>" },
  "check-circle": { vb: "0 0 24 24", body: "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M9 12.5l2 2 4.5-5\"/>" },
  "info-circle": { vb: "0 0 24 24", body: "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 11v5M12 8h.01\"/>" },
  "warning-triangle": { vb: "0 0 24 24", body: "<path d=\"M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z\"/><path d=\"M12 9v4M12 17h.01\"/>" },
  "bell": { vb: "0 0 24 24", body: "<path d=\"M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9\"/><path d=\"M13.7 21a2 2 0 0 1-3.4 0\"/>" },
  "loop": { vb: "0 0 24 24", body: "<path d=\"M17 2l4 4-4 4M21 6H7a4 4 0 0 0-4 4v1M7 22l-4-4 4-4M3 18h14a4 4 0 0 0 4-4v-1\"/>" },
  "droplet": { vb: "0 0 24 24", body: "<path d=\"M12 2.7S5 9.5 5 14.5a7 7 0 0 0 14 0C19 9.5 12 2.7 12 2.7z\"/>" },
  "backspace": { vb: "0 0 24 24", body: "<path d=\"M21 4H8l-7 8 7 8h13a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z\"/><line x1=\"18\" y1=\"9\" x2=\"12\" y2=\"15\"/><line x1=\"12\" y1=\"9\" x2=\"18\" y2=\"15\"/>" },
  "lock": { vb: "0 0 24 24", body: "<rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/>" },
  "heart": { vb: "0 0 24 24", body: "<path d=\"M12 21s-7.5-4.7-10-9.3C0.6 8.6 2.2 4.6 6 4.6c2.1 0 3.3 1.2 4 2.2.7-1 1.9-2.2 4-2.2 3.8 0 5.4 4 4 7.1C19.5 16.3 12 21 12 21z\" fill=\"#FF2D55\"/>" },
  "message": { vb: "0 0 24 24", body: "<path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"/>" },
  "info-lined": { vb: "0 0 24 24", body: "<circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"/><line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"/>" },
};
export type IconName = keyof typeof ICON_GEOM;
