/**
 * UX Review — manifest loader + shared types.
 *
 * Data source: projects/UX Review/app-map.json, generated by Project B from
 * the Luna App Map. The manifest is a flat array per the artifact contract
 * (INFRASTRUCTURE-BRIEF §6). Design-version config lives here (platform
 * concern, not part of the artifact contract).
 */
import rawManifest from "../../projects/UX Review/app-map.json";

export type ScreenStatus = "New" | "Changed" | "Unchanged";

export interface Screen {
  id: string;
  title: string;
  status: ScreenStatus;
  feature: string;
  brdTier: string;
  /** Path to the wireframe artifact, or `component:<id>` for a native render. */
  wireframe: string;
  /** Legacy (Figma screenshot) for old-vs-new compare; null when New. */
  legacy: string | null;
  brdLink?: string;
  summary?: string;
}

export const SCREENS: Screen[] = rawManifest as Screen[];

/** Design versions a comment can be stamped against (newest last). */
export const DESIGN_VERSIONS = ["v0.1 — Apr 2026", "v0.2 — May 2026"] as const;
export const CURRENT_DESIGN_VERSION = "v0.2 — May 2026";

export const STATUS_ORDER: ScreenStatus[] = ["New", "Changed", "Unchanged"];

export function getScreen(id: string): Screen | undefined {
  return SCREENS.find((s) => s.id === id);
}

/** Distinct features, in first-seen order. */
export function features(): string[] {
  return [...new Set(SCREENS.map((s) => s.feature))];
}

/** Distinct BRD tiers, sorted. */
export function tiers(): string[] {
  return [...new Set(SCREENS.map((s) => s.brdTier))].sort();
}

/** Screens grouped by feature, preserving feature first-seen order. */
export function byFeature(): { feature: string; screens: Screen[] }[] {
  return features().map((feature) => ({
    feature,
    screens: SCREENS.filter((s) => s.feature === feature),
  }));
}

/** If the wireframe is a native component render, return its registry id. */
export function componentId(wireframe: string | null): string | null {
  if (!wireframe) return null;
  return wireframe.startsWith("component:") ? wireframe.slice("component:".length) : null;
}
