/**
 * UX Review — manifest loader + shared types.
 *
 * Data source: projects/UX Review/app-map.json, generated by Project B from
 * the Luna App Map. The manifest is a flat array per the artifact contract
 * (INFRASTRUCTURE-BRIEF §6). Design-version config lives here (platform
 * concern, not part of the artifact contract).
 */
import rawManifest from "../../projects/UX Review/app-map.json";

export type ScreenStatus = "Work in Progress" | "Approved";

export interface Screen {
  id: string;
  title: string;
  /** Review workflow status. */
  status: ScreenStatus;
  feature: string;
  /** Path to the wireframe artifact, or `component:<id>` for a native render. */
  wireframe: string;
  /** Legacy (Figma screenshot) for the old-vs-new compare; null when none. */
  legacy: string | null;
  summary?: string;
}

export const SCREENS: Screen[] = rawManifest as Screen[];

/** Design versions a comment can be stamped against (newest last). */
export const DESIGN_VERSIONS = ["v0.1 — Apr 2026", "v0.2 — May 2026", "v0.3 — Jun 2026", "v0.4 — Jun 2026"] as const;
export const CURRENT_DESIGN_VERSION = "v0.4 — Jun 2026";

export const STATUS_ORDER: ScreenStatus[] = ["Work in Progress", "Approved"];

/**
 * Scenario states — the dynamic-content axis. Some screens change over time
 * (e.g. Hypo Shield's communication differs on day one vs. mid-learning vs.
 * ready). A screen listed here renders ALL its states into the DOM (each block
 * wrapped in `[data-ux-state="<id>"]`, the first visible and the rest `hidden`)
 * and the detail page shows a segmented "Scenario" control above the phone so a
 * reviewer can switch between them. Orthogonal to the New/Old variant and the
 * design-version dropdown. First entry is the default shown on load.
 */
export interface ScreenState {
  id: string;
  /** Short control label (e.g. "Days 1–7 · Establishing"). */
  label: string;
  /** One line under the control explaining what the reviewer is looking at. */
  caption: string;
}
export const SCREEN_STATES: Record<string, ScreenState[]> = {
  "hypo-learning-state": [
    {
      id: "establishing",
      label: "Days 1–7 · Establishing",
      caption: "First week of wear — Luna is building your baseline. Suggestions begin once you've had 5 sessions within a 7-day window.",
    },
    {
      id: "ready",
      label: "Ready · 5+ this week",
      caption: "Five or more sessions in the last 7 days — Hypo Shield is active and can now suggest a dose change.",
    },
    {
      id: "paused",
      label: "Paused · under 5",
      caption: "Fewer than 5 sessions in the last 7 days — suggestions pause until you're back to 5 in 7 days.",
    },
  ],
};
export function statesFor(id: string): ScreenState[] {
  return SCREEN_STATES[id] ?? [];
}

export function getScreen(id: string): Screen | undefined {
  return SCREENS.find((s) => s.id === id);
}

/** Distinct features, in first-seen order. */
export function features(): string[] {
  return [...new Set(SCREENS.map((s) => s.feature))];
}

/** Screens grouped by feature, preserving feature first-seen order. */
export function byFeature(): { feature: string; screens: Screen[] }[] {
  return features().map((feature) => ({
    feature,
    screens: SCREENS.filter((s) => s.feature === feature),
  }));
}

/** If the wireframe is a native component render, return its registry id. */
export function componentId(wireframe: string | null): string | null {
  if (!wireframe) return null;
  return wireframe.startsWith("component:") ? wireframe.slice("component:".length) : null;
}

/**
 * Prototype walkthrough wiring. The tab bar maps to the three tab-root screens;
 * FLOW_NEXT advances a screen's primary CTA to the next step in its flow. Used by
 * the detail page's "prototype mode" so you can click through the app like the
 * real thing — without changing any screen. (Screens not listed simply don't
 * advance on the primary button.)
 */
export const TAB_TARGET: Record<string, string> = {
  dashboard: "home-dashboard",
  "session-history": "session-history",
  settings: "settings-list",
};

export const FLOW_NEXT: Record<string, string> = {
  // Onboarding chapters → hand off to Apollo Training
  "onboarding-chapter-1": "onboarding-chapter-2",
  "onboarding-chapter-2": "onboarding-chapter-3",
  "onboarding-chapter-3": "onboarding-chapter-4",
  "onboarding-chapter-4": "onboarding-chapter-5",
  "onboarding-chapter-5": "apollo-training-start",
  // Apollo — evening setup → overnight → morning removal → complete
  "apollo-training-start": "apollo-intro",
  "apollo-training-gate": "onboarding-setup-landing",
  "apollo-intro": "apollo-step-01-inventory",
  "apollo-step-01-inventory": "apollo-step-02-open-tray",
  "apollo-step-02-open-tray": "apollo-step-03-fill",
  "apollo-step-03-fill": "apollo-step-05-attach-capsule",
  "apollo-step-05-attach-capsule": "apollo-pending",
  "apollo-pending": "apollo-step-06-remove-base",
  "apollo-pending-failure": "apollo-pending",
  "apollo-step-06-remove-base": "apollo-step-07-apply-body",
  "apollo-step-07-apply-body": "apollo-overnight-handoff",
  "apollo-overnight-handoff": "apollo-training-start-morning",
  "apollo-training-start-morning": "apollo-morning-start",
  "apollo-morning-start": "apollo-step-08-remove-device",
  "apollo-step-08-remove-device": "apollo-step-09-detach-reservoir",
  "apollo-step-09-detach-reservoir": "apollo-step-10-charge",
  "apollo-step-10-charge": "apollo-complete",
  "apollo-complete": "home-dashboard",
  // Hypo Shield — the peek card opens its takeover; the suggestion peek gates
  // through the full-screen review, then the two-step confirm, then success
  "hypo-home-tip-default": "hypo-learning-state",
  "hypo-home-tip-post": "hypo-recommendation-detail",
  "hypo-recommendation-detail": "dose-confirmation-spine",
  "dose-confirmation-spine": "hypo-confirm-success",
  "hypo-confirm-success": "home-dashboard",
  // IOB — pre-session opt-in → opted-in home
  "iob-pre-session-announcement": "iob-home-on",
};

/**
 * The "Flows" view — the default lens on the gallery. Instead of a flat wall of
 * 58 cards, the app is shown as a small set of journeys (each an ordered
 * sequence of screens) grouped under areas, with an app-map of how the areas
 * connect. Reframes review around continuity, not picky per-screen detail.
 *
 * Each in-scope screen appears in exactly one flow; the spine archetypes fold
 * into the flow whose pattern they define (dose-confirmation-spine → Hypo Shield,
 * hardware-checkpoint-spine → Apollo evening).
 */
export interface ReviewArea {
  id: string;
  label: string;
  blurb: string;
  /** Areas this one hands off to (drives the app-map arrows). */
  leadsTo: string[];
  /** The central daily hub. */
  hub?: boolean;
}
export interface ReviewFlow {
  id: string;
  area: string;
  label: string;
  blurb: string;
  screens: string[];
}

export const AREAS: ReviewArea[] = [
  { id: "onboarding", label: "Onboarding", blurb: "First run: meet Luna, pair your Capsule and CGM, and enter your routine.", leadsTo: ["apollo"] },
  { id: "apollo", label: "Apollo Training", blurb: "Learn to place and remove the device — evening setup, then morning removal.", leadsTo: ["home"] },
  { id: "home", label: "Home — daily", blurb: "The hub you live in: tonight's glucose, session history, and settings.", leadsTo: ["hypo", "iob"], hub: true },
  { id: "hypo", label: "Hypo Shield", blurb: "Overnight long-acting dose guidance — surface a suggestion, confirm it safely, manage it.", leadsTo: [] },
  { id: "iob", label: "IOB Display", blurb: "See how much Luna-delivered insulin is still active (opt-in).", leadsTo: [] },
];

export const FLOWS: ReviewFlow[] = [
  {
    id: "onboarding-chapters", area: "onboarding", label: "Setup chapters (1–5)",
    blurb: "The main onboarding journey, handing off to Apollo Training.",
    screens: ["onboarding-chapter-1", "onboarding-chapter-2", "onboarding-chapter-3", "onboarding-chapter-4", "onboarding-chapter-5"],
  },
  {
    id: "onboarding-setup", area: "onboarding", label: "Setup states & first-run education",
    blurb: "Landing states, routine capture, app/UI walkthroughs, and device management.",
    screens: ["onboarding-setup-landing", "onboarding-long-acting-insulin", "onboarding-ui-walkthrough", "onboarding-setup-app-walkthrough", "onboarding-session-history-intro", "onboarding-tonight-panel-states", "onboarding-settings-luna-controller"],
  },
  {
    id: "apollo-evening", area: "apollo", label: "Evening setup",
    blurb: "Training start → gate → intro → 6 steps (Luna-is-preparing check) → overnight hand-off.",
    screens: ["apollo-training-start", "apollo-training-gate", "apollo-intro", "apollo-step-01-inventory", "apollo-step-02-open-tray", "apollo-step-03-fill", "apollo-step-05-attach-capsule", "apollo-pending", "apollo-pending-failure", "apollo-step-06-remove-base", "apollo-step-07-apply-body", "apollo-overnight-handoff"],
  },
  {
    id: "apollo-morning", area: "apollo", label: "Morning removal & re-entry",
    blurb: "Morning training start → 3 removal steps → complete.",
    screens: ["apollo-training-start-morning", "apollo-morning-start", "apollo-step-08-remove-device", "apollo-step-09-detach-reservoir", "apollo-step-10-charge", "apollo-complete"],
  },
  {
    id: "home-hub", area: "home", label: "The daily hub",
    blurb: "Home dashboard ⇄ Session History ⇄ Settings, via the tab bar.",
    screens: ["home-dashboard", "session-history", "settings-list"],
  },
  {
    id: "hypo", area: "hypo", label: "Suggest → review → confirm → manage",
    blurb: "Learning states, the three suggestion entry points, the full-screen review that gates every suggestion, the two-step confirm, success & skip, settings, and how-it-works.",
    screens: ["hypo-home-tip-default", "hypo-learning-state", "hypo-home-tip-post", "hypo-push-notification", "hypo-recommendation-detail", "dose-confirmation-spine", "hypo-confirm-success", "hypo-confirm-skip", "hypo-settings", "hypo-how-it-works"],
  },
  {
    id: "iob", area: "iob", label: "Opt in → see it → manage",
    blurb: "Pre-session announcement → opted-in Home → session detail → settings toggle.",
    screens: ["iob-pre-session-announcement", "iob-home-on", "iob-session-detail", "iob-settings"],
  },
];

/** Flows belonging to an area, in declared order. */
export function flowsForArea(areaId: string): ReviewFlow[] {
  return FLOWS.filter((f) => f.area === areaId);
}
/** Total in-scope screens in an area. */
export function areaScreenCount(areaId: string): number {
  return flowsForArea(areaId).reduce((n, f) => n + f.screens.length, 0);
}

/**
 * BRD links — one per feature, pointing at the regulated Business Requirements
 * doc on Google Drive (NOT Notion). Keyed by the screen's `feature`. Adding a
 * feature = add one entry here, so every screen in that feature shares the
 * correct link and there's a single place to maintain it.
 */
export const FEATURE_BRDS: Record<string, { title: string; url: string }> = {
  "Hypo Shield & In-App Comms": {
    title: "Hypo Shield & In-App Comms — Business Requirements (BRD)",
    url: "https://docs.google.com/document/d/1XPDw5hbqG6boaocceBvnhxZZOJv9Ac28HPZJh6HnYoQ/edit",
  },
  "IOB Display": {
    title: "IOB Display — Business Requirements (BRD)",
    url: "https://docs.google.com/document/d/1EhOOcDZvF0knvRYnP44P7YtdtErg1j_l_eD0krhvhdU/edit",
  },
  "Onboarding Update": {
    title: "Onboarding Update — Business Requirements (BRD)",
    url: "https://docs.google.com/document/d/1m3lmOTehTHCxQugJqYkoXb1cZw5b42lEd3Vzhs0782o/edit",
  },
  "Training Update Apollo": {
    title: "Apollo Training — Business Requirements (BRD)",
    url: "https://docs.google.com/document/d/1h1ViWd7Uv0ue0qhOrecxdNZN10tF2zsMJGjC9l5wnlM/edit",
  },
  "Dark UI re-skin": {
    title: "Dark UI — Business Requirements (BRD)",
    url: "https://docs.google.com/document/d/12868Hp1iLILPfLYEUtxI1TeI-Se5HhIqvpS_sJD7_R8/edit",
  },
};

/** Program-level reference docs (Google Drive), surfaced for engineering. */
export const SUPPORTING_DOCS: { title: string; url: string; desc: string }[] = [
  {
    title: "Luna App Map — Screen Inventory (T1 Pivotal)",
    url: "https://docs.google.com/spreadsheets/d/1M3UuD1aWg8UJT-jOIEmONmOnzoK0aTLsPhapF6M-jOc/edit",
    desc: "Every screen × Status (New/Changed/Unchanged) × Feature × BRD tier.",
  },
  {
    title: "T1 BRD Program — Consolidated Decisions",
    url: "https://docs.google.com/document/d/1m1SzJV5rbr2Ymv6zQVJQg5l4EFD_x3Qoco5wW4ASCkE/edit",
    desc: "The locked product decisions across the slate.",
  },
  {
    title: "Two-Step Dose-Confirmation — Component Spec",
    url: "https://docs.google.com/document/d/19MZ24k-MfCuDemTLeCRKKP9pJb9K0LWHUWvxDogHHBo/edit",
    desc: "Shared dose-confirmation component (Hypo Shield / IOB / Onboarding depend on it).",
  },
];

/** Only ever return a Google Docs/Drive URL — guards against a stray Notion link. */
export function isGoogleDocUrl(url: string): boolean {
  return /^https:\/\/(docs|drive)\.google\.com\//.test(url);
}

/** The BRD for a screen's feature, if one exists and is a real Google Doc. */
export function brdFor(feature: string): { title: string; url: string } | undefined {
  const b = FEATURE_BRDS[feature];
  return b && isGoogleDocUrl(b.url) ? b : undefined;
}
